baseURL = "https://stephaniegascon.info/"
copyright = '© 2025 Stephanie Gascon'
languageCode = "en-SG"
title = "Stephanie Gascon"
defaultContentLanguageInSubdir = true

enableRobotsTXT = false

# When using ref or relref to resolve page links and a link cannot
# resolve, it will be logged with this log level.
refLinksErrorLevel = 'WARNING'

[params]
  # Site description. Used in meta description
  description = 'My personal website.'

  # SEO keywords. Used in 'meta name="keywords"' tag.
  # May be overridden by .Keywords or .Tags in front matter.
  keywords = ['TESOL', 'linguistics', 'freelance', 'education', 'design']

  # Used in site header
  tagline = 'Profile'

  # Custom footer text on left sidebar. Use HTMl if needed.
  # "&copy;" and "{year}" will be replaced by © and the current year.
  footer = 'Built with <a href="https://github.com/sergeyklay/gohugo-theme-ed" target="_blank" rel="noopener noreferrer">Ed</a>. Distributed under an MIT license. Content &copy; {year} Stephanie Gascon.'

  # Colour scheme. Options: red, orange, magenta, cyan, blue, brown
  colorScheme = 'cyan'

  # Sections to be displayed in:
  # - main page
  # - RSS feeds
  # - search index
  # - ...
  mainSections = ['posts', 'links']

  # Posts date format, for example: 2006-01-02
  dateFormat = ':date_long'
  dateFormatToc = '2006.01.02'

  # Show "Read more" button in list if true
  readmore = true

  # RSS/Atom feed size
  feedSize = 25

  recentPostsSize = 5

  [params.contact]
    # Forms Backend URL, used in contacts form
    formAction = 'https://submit-form.com/example'

    # Contact form email subject
    emailSubject = 'Contact form submission'

    # Where should the user be redirected after successful form submit?
    thanksUrl = '/thanks'

  # Site icons, relative to ./static
  [params.assets]
    # favicon.ico for legacy browsers
    favicon = 'favicon.ico'

    # 180×180 PNG image for Apple devices
    apple_touch_icon = 'apple-touch-icon.png'

  [params.seo]
    # Will be used in schema.org/Organization.
    # The site.Title  will be used if empty.
    publisher = 'Stephanie Gascon'

  showAuthor = true
  [params.author]
    name = 'Stephanie Gascon'
    email = 'mail@placeholder'
    github = 'StphnG'
    location = 'Singapore'

  [params.social]
    # Array of Facebook Page Admin IDs for Domain Insights
    facebookAdminIds = []
    # Facebook Page ID
    facebookId = ''

  # Configure search engine
  [params.search]
    enable = true
    # Maximum length (in words) of each text blurb. You can change this
    # value if you find that 100 is too short or too long for your taste.
    maxSummaryLength = 100
    # Lunr has full support for the indexing and searching of documents
    # in English. If your documents are in another language, uncomment
    # required languages below.
    #
    # For more see: https://lunrjs.com/guides/language_support.html
    languages = ['en','ja']

  [params.comments]
    enable = false
    type = 'giscus'

    # Configure giscus comments.
    #
    # For more see: https://giscus.app/
    [params.comments.giscus]
      # Required parameters:
      repo = ''
      repoId = ''
      category = ''
      categoryId = ''

      # Optional parameters:
      theme = 'light'
      mapping = 'pathname'
      strict = 0
      reactionsEnabled = 1
      emitMetadata = 0
      inputPosition = 'bottom'

  [params.privacy]
    [params.privacy.googleTagManager]
      disable = false
      respectDoNotTrack = true

  [params.services]
    [params.services.googleTagManager]
      id = ''

[languages]
  [languages.en]
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
	contentDir = 'content/en'
	
 [languages.ja]
    languageCode = 'ja'
    languageDirection = 'ltr'
    languageName = '日本語'
	title = "ステファニー・ガスコン" 
    weight = 2
	contentDir = 'content/ja'

# For more see https://gohugo.io/content-management/menus/
[languages.en.menus]

  [[languages.en.menus.main]]        # sections in the website sidebar
    name = 'Home'       # menu item display title
    pageRef = '/'       # path to the page
    weight = 1          # order of the menu item
  [[languages.en.menus.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 2
  [[languages.en.menus.main]]
    name = 'Links'
    pageRef = '/links'
    weight = 3
  [[languages.en.menus.main]]
    name = 'Search'
    pageRef = '/search'
    weight = 4

  [[languages.en.menus.feeds]]
    name = 'RSS 2.0'
    url = '/rss.xml'
    weight = 1
	
[languages.ja.menus]

  [[languages.ja.menus.main]]        # sections in the website sidebar
    name = 'ホーム'       # menu item display title
    pageRef = '/ja/'       # path to the page
    weight = 1          # order of the menu item
  [[languages.ja.menus.main]]
    name = 'ブログ'
    pageRef = '/ja/posts'
    weight = 2
  [[languages.ja.menus.main]]
    name = 'リンク'
    pageRef = '/ja/links'
    weight = 3
  [[languages.ja.menus.main]]
    name = '検索'
    pageRef = '/search'
    weight = 4

  [[languages.ja.menus.feeds]]
    name = 'RSS 2.0'
    url = '/rss.xml'
    weight = 1
	
[pagination]
  pagerSize = 10

# We have just the default tags taxonomy, and remove the categories
# taxonomy for site as not used.
[taxonomies]
  tag = 'tags'
  category = 'categories'

[outputs]
  home = ['html', 'rss', 'json', 'manifest', 'humanstxt']
  page= ['html']
  rss = ['rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[outputFormats]

  [outputFormats.manifest]
    # The .webmanifest extension is specified in the Media type registration
    # section of the specification (the response of the manifest file should
    # return Content-Type: application/manifest+json).
    #
    # For more see: https://w3c.github.io/manifest/#media-type-registration=
    name = 'manifest'
    mediaType = 'application/manifest+json'
    baseName = 'manifest'
    rel = 'manifest'
    isPlainText = true
    isHTML = false
    noUgly = false
    notAlternative = false

  # For more see: https://gohugo.io/templates/output-formats/
  [outputFormats.humanstxt]
    name = 'humanstxt'
    mediaType = 'text/plain'
    baseName = 'humans'
    rel = 'author'
    isPlainText = true
    isHTML = false
    noUgly = true
    notAlternative = true

  [outputFormats.rss]
    baseName = 'rss'
    mediaType = 'application/rss+xml'

[mediaTypes]
  [mediaTypes.'text/xml']
    suffixes = ['xml']
  [mediaTypes.'application/feed+json']
    suffixes = ['json']

# Sitemap config
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

# For more see https://gohugo.io/getting-started/configuration-markup/
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    # false due to generated Syntax Highlighter CSS
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        # Enable custom attribute support for blocks
        block = true

# If enableGitInfo is true, it will override any lastmod dates in our
# front matter. We should at least allow ourselves to manually override
# this value in the front matter.
[frontmatter]
  lastmod = ['lastmod', ':git', 'modified', 'date', 'publishdate', 'pubdate', 'published']

[module]
  [module.hugoVersion]
    extended = true
    min = '0.121.0'
  [[module.imports]]
    # Use full path to theme's repository. This is replaced in go.mod for
    # exampleSite to point to the directory above.
    path = 'github.com/sergeyklay/gohugo-theme-ed'

[minify]
  # Do not minify XML files to avoid CDATA escape issues
  disableXML = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepQuotes = true

[build]
  # This is used to dump and array of the class attributes, id attributes,
  # and tags of every HTML element within your published site.
  # This datd can be used as a source when removing unused CSS from site.
  # For more see: https://gohugo.io/hugo-pipes/postprocess/#css-purging-with-postcss
  [build.buildStats]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = true